In [1]:
import numpy as np

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a = np.array([[1,2,3],[4,5,6]]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a.shape

(2, 3)

In [5]:
b = np.arange(1,30,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [6]:
b.reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [7]:
c = np.linspace(1,5,20)
c

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [8]:
c.resize(5,4)
c

array([[1.        , 1.21052632, 1.42105263, 1.63157895],
       [1.84210526, 2.05263158, 2.26315789, 2.47368421],
       [2.68421053, 2.89473684, 3.10526316, 3.31578947],
       [3.52631579, 3.73684211, 3.94736842, 4.15789474],
       [4.36842105, 4.57894737, 4.78947368, 5.        ]])

In [9]:
d = np.ones((2,2))
d

array([[1., 1.],
       [1., 1.]])

In [10]:
e = np.zeros((3,3))
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [12]:
np.diag(f)

array([1., 1.])

In [13]:
g = np.array([1,2,3]*5)
g

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [14]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [15]:
g = np.random.rand(2,3)
print(g)
h = np.random.rand(2,3)
print(h)

[[0.3171877  0.36861048 0.22496372]
 [0.97196067 0.95170997 0.30028445]]
[[0.8003424  0.70262118 0.40049878]
 [0.21645783 0.20204599 0.49851046]]


In [16]:
i = np.vstack([h,g])
i

array([[0.8003424 , 0.70262118, 0.40049878],
       [0.21645783, 0.20204599, 0.49851046],
       [0.3171877 , 0.36861048, 0.22496372],
       [0.97196067, 0.95170997, 0.30028445]])

In [17]:
j = np.hstack([h,g])
j

array([[0.8003424 , 0.70262118, 0.40049878, 0.3171877 , 0.36861048,
        0.22496372],
       [0.21645783, 0.20204599, 0.49851046, 0.97196067, 0.95170997,
        0.30028445]])

In [18]:
k = np.random.rand(2,2)
l = np.random.rand(2,2)
print(k)
print(l)

[[0.2365952  0.25900127]
 [0.45669763 0.3041038 ]]
[[0.23122735 0.75227363]
 [0.52348441 0.69105565]]


In [19]:
m = k + l
m

array([[0.46782255, 1.0112749 ],
       [0.98018205, 0.99515945]])

In [20]:
n = k-l
n

array([[ 0.00536784, -0.49327235],
       [-0.06678678, -0.38695185]])

In [21]:
p = k**2
p

array([[0.05597729, 0.06708166],
       [0.20857273, 0.09247912]])

In [22]:
q = k.dot(l)
q

array([[0.19029041, 0.35696862],
       [0.26479458, 0.55371423]])

In [23]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [24]:
a.T

array([[1, 3],
       [2, 4]])

In [25]:
a.dtype

dtype('int64')

In [26]:
c = np.array([1,2,3,4,5])
c.sum()

15

In [27]:
c.max()

5

In [28]:
c.mean()

3.0

In [29]:
c.argmax()

4

In [30]:
c.argmin()

0

In [31]:
d = np.arange(10)**2
d

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [32]:
d[2]

4

In [33]:
d[1:5]

array([ 1,  4,  9, 16])

In [34]:
d[-1:]

array([81])

In [35]:
d[1:10:2] #d[start:stop:stepsize]

array([ 1,  9, 25, 49, 81])

In [36]:
e = np.arange(36)
e.resize(6,6)
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [37]:
e[1,2]

8

In [38]:
e[1, 2:6]

array([ 8,  9, 10, 11])

In [39]:
e[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [40]:
e[e>20]
e[e>20] = 20
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [41]:
f = e.copy()
f

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20]])

In [43]:
g = np.random.randint(1,10,(4,4))
g

array([[7, 1, 3, 1],
       [3, 1, 8, 1],
       [6, 2, 6, 5],
       [3, 3, 3, 5]])